### ISSUE TITLE
Kit is missing pieces

### ISSUE THREAD

**Issue by christiancompton** [IBM/swift-kitura-hyper-protect-dbaas#1]
This starterkit is missing a lot of pieces:

1. Unlike the other starterkits that require services and provision them automatically,  the Hypersecure service must be added manually (provisioning takes about 5 minutes and it requires a term agreement from the user, password security requirements, etc.).  If this service is not added, service enablement does not produce the proper instrumentation code - in this case we are missing the MongoDB drivers.

1. I suspect because of this same problem, this kit is missing a localdev-config.json

1. We need to add instructions to the README about how to provision this service.  Now that the service just moved to Beta from experimental, users can select the database type in the "plans" section.  This kit only works for MONGO at this time, so we need to tell users to select these plans.

**Comment by dolph** [comment]
This definitely seems like the most complicated of the starter kit -> code pattern conversions, so I've been saving it for last :) Thanks for the specific pointers on what needs to be done!
